services:
#    medical.example:
#        class: Medical\MedicalBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    app.condition.repository:
        class: Medical\MedicalBundle\Repository\ConditionRepository
        arguments: [MedicalBundle:Condition]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository