Medical\MedicalBundle\Entity\Condition:
    type: entity
    table: conditions
    repositoryClass: Medical\MedicalBundle\Repository\ConditionRepository
    fields:
        id:
            type: integer
            generator:
                strategy: AUTO
            id: true
        name: { type: string, length: 255 }
    manyToMany:
        symptoms:
            targetEntity: Medical\MedicalBundle\Entity\Symptom
            mappedBy: conditions