Medical\MedicalBundle\Entity\Symptom:
    type: entity
    table: symptoms
    repositoryClass: Medical\MedicalBundle\Repository\SymptomRepository
    fields:
        id:
            type: integer
            generator:
                strategy: AUTO
            id: true
        name: { type: string, length: 255 }
    manyToMany:
        conditions:
            targetEntity: Medical\MedicalBundle\Entity\Condition
            inversedBy: symptoms
            joinTable:
                name: condition_symptom
                joinColumns:
                    symptom_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    condition_id:
                        referencedColumnName: id