Medical\UserBundle\Entity\User:
    type: entity
    table: users
    fields:
        id:
            type: integer
            generator:
                strategy: AUTO
            id: true
        email_new:
            type: string
            nullable: true
            length: 255
    oneToOne:
        UserProfile:
            targetEntity: Medical\UserBundle\Entity\UserProfile
            mappedBy: User
            cascade: ["persist", "merge"]
    oneToMany:
        conditions:
            targetEntity: Medical\MedicalBundle\Entity\Condition
            mappedBy: user