security:
    encoders:
        Medical\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login_admin
                check_path: /admin/login_check
                default_target_path: /admin
            context: my_context

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            context: my_context

            anonymous: true
            logout:
                path: /logout
                target: /
                invalidate_session: false

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
